# vim:fileencoding=utf-8:foldmethod=marker
### Custom aliases ###

# Source localized aliases if available
if [ -x ~/.bash.d/bash_aliases.this ]; then
    source ~/.bash.d/bash_aliases.this
fi

### Files, filesystems and directories ### {{{

# Enable color support of ls and grep and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    eval "`dircolors -b`"
    alias ls='ls --color=auto'
    alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

alias df='df -hT'

# File tree of directories only
alias dirtree="ls -R | grep :*/ | grep ":$" | sed -e 's/:$//' -e 's/[^-][^\/]*\//--/g' -e 's/^/   /' -e 's/-/|/'"

alias ls='ls --color=auto -F --group-directories-first'
alias lsa='ls -aF'
alias ll='ls -la'
alias lsdirs='ls --color=auto -FlA | grep :*/'      # Show directories only
alias lsexe='ls --color=auto -FlA | grep \*'        # Show executables only
alias lshid='ls --color=auto -dF .*'
alias mount='mount | column -t'
alias path="echo $PATH | tr -s ':' '\n'"            # Pretty print $PATH
alias r='fc -s'
alias fzfp="fzf --preview 'bat --color=always {}' --preview-window '~3'"

# Change to root of git project
alias groot='cd $(git rev-parse --show-cdup)'
# }}}

### Network aliases ### {{{

alias pingalocal='echo 192.168.0.{1..255} | xargs -n1 ping -c1'
alias asn-whois='whois -h whois.cymru.com " -v $1"'

if [[ -n $TEXTBROWSER ]];
then
    alias whatsmyip="$TEXTBROWSER -dump checkip.dyndns.org"
else
    alias whatsmyip="curl ifconfig.me; echo"
fi
# }}}

### Misc aliases ### {{{

# Nice way to see memory usage
alias freem='egrep --color=NEVER "Mem|Cache|Swap" /proc/meminfo' 
alias fingerprints='ssh-keygen -lv -f ~/.ssh/known_hosts'
alias topcommands='cut -f1 -d " " ~/.bash_history | sort | uniq -c | sort -nr | head -12'
alias vimsplit='vim -O '        # Edit multiple files split horizontally 
alias vissh='vim ~/.ssh/config'
if [[ $(command -v kitty) ]]
then
	alias icat='kitty +icat'
	alias unicode='kitty +kitten unicode_input'
fi
alias checkvpn='curl -s https://www.ovpn.com/v2/api/client/ptr | python3 -m json.tool'
if [[ $(command -v distrobox) ]]
then
	alias fedora='distrobox enter fedora'
fi
# }}}

# Security {{{
alias firechrome='firejail --name=firechrome --private google-chrome --no-first-run'
alias cyberchef='podman run -d -p 8000:8000 cyberchef:latest'
alias remnux='podman run --rm -it -v /home/krister/IRT:/home/remnux/IRT:z -u remnux docker.io/remnux/remnux-distro:focal bash'
alias pwsh='podman run --mount 'type=volume,src=powershell_scripts,dst=/home' -it powershell:latest'
alias safecurl='podman run --rm --cap-drop=all -it curlimages/curl /bin/sh'
# }}}
